spring.redis.database: 0
spring.redis.host: localhost
spring.redis.port: 6379
# 连接超时时间 单位 ms（毫秒）
spring.redis.timeout: 3000

# 连接池中的最大空闲连接，默认值也是8。
spring.redis.pool.max-idle: 8
#连接池中的最小空闲连接，默认值也是0。
spring.redis.pool.min-idle: 0
# 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
spring.redis.pool.max-active: 8
# 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出JedisConnectionException
spring.redis.pool.max-wait: -1

mybatis.table.auto: update
mybatis.model.pack: com.schedule.myschedule.entity
mybatis.database.type: mysql
mybatis.model.packs: com.schedule.myschedule.entity.*
mybatis.model.mappers: com.schedule.myschedule.mapper.*
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&autoReconnect=true
    username: root
    password: axuanam45

server:
  port: 8080

spring.thymeleaf.prefix: classpath:/templates/

